- hosts: chroot
  connection: chroot
  become: true
  tasks:

    - name: install docker dependencies
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: add GPG keys
      apt_key:
        url: "{{ item }}"
        state: present
      loop:
        - https://download.docker.com/linux/ubuntu/gpg
        - https://apt.releases.hashicorp.com/gpg

    - name: Adding repository  
      apt_repository:
        repo: "{{ item }}"
        update_cache: true
      become: yes
      loop:
        - deb https://download.docker.com/linux/ubuntu focal stable
        - deb [arch=amd64] https://apt.releases.hashicorp.com focal main

    - name: Update apt-get repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
      become: true

    - name: Installing packages
      apt:
        name: "{{ item }}"
      become: true
      loop:
        - bridge-utils
        - containerd.io
        - curl
        - docker-ce
        - docker-ce-cli
        - git
        - gpg
        - libvirt-clients
        - libvirt-daemon-system
        - libvirt-dev
        - lsb-release
        - packer=1.6.1
        - qemu-kvm
        - rsyslog
        - software-properties-common
        - sudo
        - vagrant=2.2.16
        - vim
        - virt-manager
        - wget
    - name: Prevent vagrant and packer from being upgraded
      dpkg_selections:
         name: "{{ item }}"
         selection: hold
      loop:
        - vagrant
        - packer

    - name: Make sure that docker is active
      service:
        name: docker
        state: started
        enabled: yes

    - name: Installing requirements via pip3
      pip:
        name: ['pywinrm', 'pypsrp']
        state: latest
        executable: pip3

    - name: Installing vagrant plugin vagrant-libvirt
      shell: 'vagrant plugin install vagrant-libvirt'

    - name: Check if the windows iso exists
      stat:
        path: 17763.379.190312-0539.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso
      register: p

    - debug:
        msg: "17763.379.190312-0539.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso file exists..."
      when: p.stat.exists

    - debug:
        msg: "17763.379.190312-0539.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso file not found"
      when: p.stat.exists == False

    - name: Download windows iso
      get_url:
        url: https://software-download.microsoft.com/download/sg/17763.379.190312-0539.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso
        dest: '.'
      become: true
      when: p.stat.exists == False


    - name: Check if the virtio-win iso exists
      stat:
        path: virtio-win.iso
      register: p

    - debug:
        msg: "virtio-win.iso file exists..."
      when: p.stat.exists

    - debug:
        msg: "virtio-win.iso file not found"
      when: p.stat.exists == False

    - name: Download virtio-win iso
      get_url:
        url: https://fedorapeople.org/groups/virt/virtio-win/direct-downloads/latest-virtio/virtio-win.iso
        dest: './virtio-win.iso'
      become: true
      when: p.stat.exists == False

    - name: Check if the vagrant_2.2.16_x86_64.deb exists
      stat:
        path: vagrant_2.2.16_x86_64.deb
      register: p

    - debug:
        msg: "vagrant_2.2.16_x86_64.deb file exists..."
      when: p.stat.exists

    - debug:
        msg: "vagrant_2.2.16_x86_64.deb file not found"
      when: p.stat.exists == False

    - name: Download vagrant_2.2.16_x86_64.deb
      get_url:
        url: https://releases.hashicorp.com/vagrant/2.2.16/vagrant_2.2.16_x86_64.deb 
        dest: '.'
      become: true
      when: p.stat.exists == False

    - name: Copy packer files to chroot
      copy:
        src: "{{ item  }}"
        dest: "/"
        mode: preserve
      loop:
        - answer_files
        - scripts
        - Vagrantfile
        - vagrantfile-windows_2016.template
        - win_dev-Ansible.yml
        - windows_2019.json
        - startup.sh
        - Dockerfile
      tags:
        - copy

    - name: ensure custom facts directory exists
      file: >
         path=/etc/samba
         recurse=yes
         state=directory
      tags:
        - copy

    - name: Copy packer files to chroot
      copy:
        src: "{{ item  }}"
        dest: "/{{ item }}"
      loop:
        - etc/samba/smb.conf 
      tags:
        - copy
              

    - name: Packer build
      shell: 'packer build --on-error=abort --only=qemu --var iso_url=17763.379.190312-0539.rs5_release_svc_refresh_SERVER_EVAL_x64FRE_en-us.iso --var iso_checksum="sha256:221f9acbc727297a56674a0f1722b8ac7b6e840b4e1ffbdd538a9ed0da823562" --var headless="true" windows_2019.json'
      tags:
        - packer
      
    
    - name: Packer build
      shell: 'vagrant box add win_dev-Ansible windows_2019_libvirt.box'


    - name: docker build
      shell: DOCKER_BUILDKIT=1 docker build -t ghcr.io/fabceolin/windev:usb -f Dockerfile .
      tags:
        - docker
