---
- hosts: all
  # site commands windows => https://www.windows-commandline.com/
  gather_facts: true
  vars:
    ansible_user: vagrant
    ansible_password: vagrant
    ansible_connection: ssh
    ansible_port: 32022
    ansible_ssh_extra_args: '-o StricthostKeyChecking=no'
    ansible_ssh_common_args: '-o userknownhostsfile=/dev/null'
    ansible_host_key_checking: False
    ansible_shell_type: cmd
    ansible_ssh_host_key_checking: False
    ansible_paramiko_host_key_checking: False
    host_key_checking: False
    prefix: /mingw64
    ssh_host_key_checking: False
    paramiko_host_key_checking: False 
    #comentario
  tasks:

   - name: Install chocolatey
     win_shell: powershell -NoProfile -InputFormat None -ExecutionPolicy Bypass -Command "[System.Net.ServicePointManager]::SecurityProtocol = 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))" && SET "PATH=%PATH%;%ALLUSERSPROFILE%\chocolatey\bin"
     args:
       executable: cmd


   - name: Install packages
     win_chocolatey:
      name: "{{ item }}"
      state: present
      timeout: 18500
     loop:
      - 7zip.portable
      - firefox
      - microsoft-office-deployment
     tags:
      - packages

   - name: Add a PowerShell module
     win_psmodule:
       name: "{{ item }}"
       state: present
       allow_clobber: yes
     loop:
       - pscx
     tags:
       - powershell
       - pscx

   - name: Configure the ssh service
     win_service:
       name: sshd
       start_mode: auto
       state: started
     tags:
       - ssh
   - name: "Download Mesa drivers"
     ansible.windows.win_get_url:
         url: "https://github.com/pal1000/mesa-dist-win/releases/download/21.1.3/mesa3d-21.1.3-release-msvc.7z"
         dest: C:\mesa3d-21.1.3-release-msvc.7z
         force: no
     tags:
         - 3d

   - name: "Unzip the Mesa drivers"
     community.windows.win_unzip:
         src: C:\mesa3d-21.1.3-release-msvc.7z
         dest: C:\mesa\ 
         delete_archive: yes
     tags:
         - 3d

   - name: "Install Mesa drivers"
     win_shell: "c:\\tools\\msys64\\usr\\bin\\echo.exe -e -n 22\\n | c:\\tools\\msys64\\usr\\bin\\pv.exe -q -L 1 | c:\\tools\\msys64\\usr\\bin\\timeout.exe 5s c:/mesa/systemwidedeploy.cmd"
     ignore_errors: yes
     tags: 
         - 3d
         - 3d-deploy

   - name: Set 3d environment variables
     ansible.windows.win_environment:
        state: present
        name: MESA_GL_VERSION_OVERRIDE
        value: 3.2
        level: machine
     tags:
       - environment
       - 3d
       - 3d-environment

   - name: Set 3d environment variables
     ansible.windows.win_environment:
        state: present
        name: GALLIUM_DRIVER
        value: swr
        level: machine
     tags:
       - environment
       - 3d
       - 3d-environment
   
   - name: Reboot for winrm
     win_reboot:
        reboot_timeout: 18000


